version: '3.0'
services:
  rasa:
    image: rasa/rasa:3.2.9-full
    container_name: rasa
    ports:
      - 5005:5005
    volumes:
      - ./:/app
    command: ["run", "-m", "models", "--enable-api",  "--debug", "--endpoints","endpoints.yml", "--cors","*"]

  app:
    image: chatbot-actions
    container_name: rasa_actions
    ports:
      - 5055:5055